### ISSUE TITLE
BUG: Duplicate controls for "Number" under the TDMorph tab

### ISSUE THREAD

**Issue by DarienBrito** [ruigato/geoMusica#2]
**Describe the bug**
Duplicate controls for number under the TDMorph tab

**To Reproduce**
1. Click on TDMorph
2. There are 2 "Number" parameters

**Expected behavior**
Should only be one

**Comment by ruigato** [comment]
this happens because the layer system i'm using for the widgets, may need your help to include automatically the layer number on the label of the TDMorph param!

**Comment by ruigato** [comment]
solved with customName attr in TDMorph createElement()
