### ISSUE TITLE
BUG: Audio is outputed to every single available channel

### ISSUE THREAD

**Issue by DarienBrito** [ruigato/geoMusica#3]
**Describe the bug**
Don't know if its on purpose, but the audio output of geoMusica goes to every single available channel in a soundcard by default.

**To Reproduce**

1. Output sound from geoMusica and inspect the audio buses of current sound card.

**Expected behavior**
Audio routing should be left as decision to the user.

**Comment by ruigato** [comment]
Fixed, now there's a option for setting the audio outputs
