### ISSUE TITLE
BUG: bat file has misleadingly formed start commands

### ISSUE THREAD

**Issue by bangnoise** [ruigato/geoMusica#5]
**Describe the bug**
A fairly minor issue, but geoMusica.2020.25380.WIN.bat has `start` commands with an executable path as the title argument - `start` treats the first non-terminating argument as a title, so changing to the following works as intended

    start "geoMusica" "%programfiles%\derivative\TouchDesigner099.2020.25380\bin\TouchDesigner.exe" "%~dp0\toe\geoMusicaUI.toe"

Without the "geoMusica" title, it treats the executable path as a title and the .toe path as the command and uses whatever installed copy of TouchDesigner is registered to handle .toe files - which may or may not be the one intended.

**To Reproduce**
1. Have two installed versions of TouchDesigner, with the more recent installation **not** 2020.25380
2. Launch geoMusica.2020.25380.WIN.bat
3. Observe the wrong version of TouchDesigner is launched

**Expected behavior**
The version of TouchDesigner specified in the .bat file should be launched.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ruigato** [comment]
.bat file now corrected, thank you bangnoise!
